// Generated by https://quicktype.io

export interface RespGame {
  ok: boolean;
  data: Game[] | Game;
}

export interface Game {
  id: string;
  date: string;
  salesCount: number;
  production: string;
  price: number;
  name: string;
  genre: string;
  discount: number;
  description: string;
  developer: string;
  stock: number;
  platforms: string;
  img: string;
  logo: string;
}
